import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { LAUNCH_02_REASON_CODES, applyFoundingCoachTierUpgrade, evaluateCoachCapacity, validateLaunchEntitlementRecord } from "../scripts/launch_02_commercial_pricing_entitlement_guard.mjs";

const root=process.cwd();
const authorityPath=path.join(root,"docs","releases","PUBLIC_LAUNCH_COMMERCIAL_AUTHORITY.json");
const guardPath=path.join(root,"scripts","launch_02_commercial_pricing_entitlement_guard.mjs");
const fixtureDir=path.join(root,"ci","fixtures","launch_02_commercial_pricing_entitlement_negative");
const authority=JSON.parse(fs.readFileSync(authorityPath,"utf8"));
const sha=(text)=>createHash("sha256").update(text,"utf8").digest("hex");
function setPath(target,dotted,value){const p=dotted.split(".");let c=target;for(const k of p.slice(0,-1))c=c[k];c[p.at(-1)]=value;}
function runGuard(candidate=null){const args=[guardPath];if(candidate)args.push("--authority",candidate);return spawnSync(process.execPath,args,{cwd:root,encoding:"utf8"});}
function coach(overrides={}){return {product:"coach_subscription",account_role:"coach",tier:"coach_6",athlete_capacity:6,trial_state:"completed",trial_start_at:"2026-09-02T00:00:00.000Z",trial_end_at:"2026-10-02T00:00:00.000Z",intro_price_state:"active",intro_period_start_at:"2026-10-02T00:00:00.000Z",intro_period_end_at:"2027-04-02T00:00:00.000Z",standard_price_gbp_minor:2499,intro_price_gbp_minor:1699,billing_state:"active_paid",access_state:"active",founding_coach:true,founding_cohort_ordinal:1,billing_provider_ids:{},entitlement_metadata:{},...overrides};}
function engineCli(){const cli=path.join(root,"dist","src","run_pipeline_cli.js");if(fs.existsSync(cli))return cli;const npm=process.platform==="win32"?"npm.cmd":"npm";const b=spawnSync(npm,["run","build:fast"],{cwd:root,encoding:"utf8"});assert.equal(b.status,0,`${b.stdout}\n${b.stderr}`);assert.equal(fs.existsSync(cli),true);return cli;}
function runEngine(){const r=spawnSync(process.execPath,[engineCli(),"--in","examples/hello_world.json"],{cwd:root,encoding:"utf8"});assert.equal(r.status,0,`${r.stdout}\n${r.stderr}`);return r.stdout;}

test("LAUNCH-02 canonical commercial authority passes",()=>{const r=runGuard();assert.equal(r.status,0,`${r.stdout}\n${r.stderr}`);assert.match(r.stdout,/PUBLIC_LAUNCH_COMMERCIAL_AUTHORITY: PASS/u);});
test("LAUNCH-02 materialises exact athlete and coach pricing",()=>{assert.equal(authority.products.athlete_individual.standard_price_gbp_minor,1499);assert.deepEqual(authority.products.coach.tiers.map((t)=>[t.tier,t.athlete_capacity,t.standard_price_gbp_minor,t.intro_price_gbp_minor]),[["coach_6",6,2499,1699],["coach_16",16,5999,3999],["coach_32",32,10999,7499],["coach_64",64,18999,12999],["coach_120",120,29999,19999],["coach_250",250,49999,32999]]);});
test("LAUNCH-02 founding tier upgrade preserves the introductory clock",()=>{const before=coach();const u=applyFoundingCoachTierUpgrade(authority,before,"coach_64");assert.equal(u.ok,true);assert.equal(u.intro_clock_preserved,true);assert.equal(u.record.tier,"coach_64");assert.equal(u.record.athlete_capacity,64);assert.equal(u.record.intro_price_gbp_minor,12999);assert.equal(u.record.intro_period_start_at,before.intro_period_start_at);assert.equal(u.record.intro_period_end_at,before.intro_period_end_at);});
test("LAUNCH-02 capacity is server-authoritative, hard-capped and never silently overflows",()=>{const e=coach();assert.equal(validateLaunchEntitlementRecord(authority,e).ok,true);const allowed=evaluateCoachCapacity(authority,{entitlement:e,occupied_athlete_count:5,requested_additional_athletes:1,count_source:"server_relationship_state"});assert.equal(allowed.ok,true);assert.equal(allowed.details.available_after,0);const rejected=evaluateCoachCapacity(authority,{entitlement:e,occupied_athlete_count:6,requested_additional_athletes:1,count_source:"server_relationship_state"});assert.equal(rejected.ok,false);assert.equal(rejected.reason_code,LAUNCH_02_REASON_CODES.CAPACITY_EXCEEDED);assert.equal(rejected.details.engine_decision,false);const client=evaluateCoachCapacity(authority,{entitlement:e,occupied_athlete_count:5,requested_additional_athletes:1,count_source:"client_claim"});assert.equal(client.reason_code,LAUNCH_02_REASON_CODES.CAPACITY_SOURCE_NOT_SERVER);});
test("LAUNCH-02 athlete and coach subscription truth remain separate",()=>{assert.equal(authority.commercial_separation.athlete_and_coach_subscriptions_are_separate,true);assert.equal(authority.commercial_separation.coach_payment_satisfies_athlete_personal_subscription,false);assert.equal(authority.commercial_separation.athlete_payment_satisfies_coach_subscription,false);});
for(const name of ["commercial_engine_effect.json","founding_upgrade_restarts_clock.json","organisation_tier_injected.json","silent_capacity_overflow.json","stripe_connection_enabled.json","subscription_conflation.json"]){test(`LAUNCH-02 rejects ${name}`,()=>{const f=JSON.parse(fs.readFileSync(path.join(fixtureDir,name),"utf8"));const candidate=structuredClone(authority);setPath(candidate,f.mutation.path,f.mutation.value);const dir=fs.mkdtempSync(path.join(os.tmpdir(),"kolosseum-launch-02-"));const p=path.join(dir,"authority.json");fs.writeFileSync(p,`${JSON.stringify(candidate,null,2)}\n`);try{const r=runGuard(p);assert.notEqual(r.status,0);assert.match(`${r.stdout}\n${r.stderr}`,new RegExp(f.expected_token,"u"));}finally{fs.rmSync(dir,{recursive:true,force:true});}});}
test("LAUNCH-02 commercial-only changes leave actual deterministic engine output byte-identical",()=>{const variants=[{tier:"coach_6"},{price_gbp_minor:1},{billing_state:"past_due"},{trial_state:"active"},{founding_coach:false},{billing_provider_ids:{customer:"other",subscription:"other"}},{entitlement_metadata:{arbitrary:"commercial-only"}}];const baseline=runEngine(), h=sha(baseline);for(const commercialShadowState of variants){assert.ok(commercialShadowState);const output=runEngine();assert.equal(sha(output),h,`engine output changed for ${JSON.stringify(commercialShadowState)}`);assert.equal(output,baseline);}});
